import { PlatformStaffFunction, PlatformStaffPermissions, PlatformStaffMember } from "../types";

export const DEFAULT_PERMISSIONS_BY_FUNCTION: Record<PlatformStaffFunction, PlatformStaffPermissions> = {
  "Administrateur plateforme": {
    canManageSchools: true,
    canSuspendSchools: true,
    canManageInternalStaff: true,
    canViewPlatformFinances: true,
    canManagePlatformFinances: false,
    canManageServerMaintenance: true,
    canAccessKillSwitches: true,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: true,
    canNotifySchoolsForMissingPhotos: true,
    canManagePlatformCommunications: true,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: true,
    canAuditLogs: true,
    canManageCommercialLeads: true,
    canManageTrainingModules: true
  },
  "Support technique": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: true,
    canAccessKillSwitches: false,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: true,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: false,
    canManageSecurityAlerts: true,
    canAuditLogs: true,
    canManageCommercialLeads: false,
    canManageTrainingModules: false
  },
  "Support utilisateurs": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: true,
    canNotifySchoolsForMissingPhotos: true,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: false,
    canManageSecurityAlerts: false,
    canAuditLogs: false,
    canManageCommercialLeads: false,
    canManageTrainingModules: true
  },
  "Responsable des établissements": {
    canManageSchools: true,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: true,
    canNotifySchoolsForMissingPhotos: true,
    canManagePlatformCommunications: true,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: false,
    canAuditLogs: false,
    canManageCommercialLeads: true,
    canManageTrainingModules: true
  },
  "Responsable commercial": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: false,
    canViewMissingPhotosAlerts: false,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: true,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: false,
    canAuditLogs: false,
    canManageCommercialLeads: true,
    canManageTrainingModules: false
  },
  "Comptable de la plateforme": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: true,
    canManagePlatformFinances: true,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: false,
    canViewMissingPhotosAlerts: false,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: false,
    canAuditLogs: true,
    canManageCommercialLeads: false,
    canManageTrainingModules: false
  },
  "Responsable financier": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: true,
    canManagePlatformFinances: true,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: false,
    canViewMissingPhotosAlerts: false,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: false,
    canAuditLogs: true,
    canManageCommercialLeads: true,
    canManageTrainingModules: false
  },
  "Responsable technique": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: true,
    canAccessKillSwitches: true,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: true,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: true,
    canAuditLogs: true,
    canManageCommercialLeads: false,
    canManageTrainingModules: false
  },
  "Responsable formation": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: false,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: true,
    canViewNationalAnalytics: false,
    canManageSecurityAlerts: false,
    canAuditLogs: false,
    canManageCommercialLeads: false,
    canManageTrainingModules: true
  },
  "Responsable communication": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: false,
    canViewMissingPhotosAlerts: false,
    canNotifySchoolsForMissingPhotos: true,
    canManagePlatformCommunications: true,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: false,
    canAuditLogs: false,
    canManageCommercialLeads: true,
    canManageTrainingModules: true
  },
  "Analyste": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: false,
    canViewMissingPhotosAlerts: true,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: true,
    canManageSecurityAlerts: false,
    canAuditLogs: true,
    canManageCommercialLeads: false,
    canManageTrainingModules: false
  },
  "Autre": {
    canManageSchools: false,
    canSuspendSchools: false,
    canManageInternalStaff: false,
    canViewPlatformFinances: false,
    canManagePlatformFinances: false,
    canManageServerMaintenance: false,
    canAccessKillSwitches: false,
    canManageSupportTickets: true,
    canViewMissingPhotosAlerts: false,
    canNotifySchoolsForMissingPhotos: false,
    canManagePlatformCommunications: false,
    canViewNationalAnalytics: false,
    canManageSecurityAlerts: false,
    canAuditLogs: false,
    canManageCommercialLeads: false,
    canManageTrainingModules: false
  }
};

export const OWNER_FULL_PERMISSIONS: PlatformStaffPermissions = {
  canManageSchools: true,
  canSuspendSchools: true,
  canManageInternalStaff: true,
  canViewPlatformFinances: true,
  canManagePlatformFinances: true,
  canManageServerMaintenance: true,
  canAccessKillSwitches: true,
  canManageSupportTickets: true,
  canViewMissingPhotosAlerts: true,
  canNotifySchoolsForMissingPhotos: true,
  canManagePlatformCommunications: true,
  canViewNationalAnalytics: true,
  canManageSecurityAlerts: true,
  canAuditLogs: true,
  canManageCommercialLeads: true,
  canManageTrainingModules: true
};

export const DEFAULT_INTERNAL_PORTALS: import("../types").InternalPortalConfig[] = [
  {
    id: "portal-owner-governance",
    name: "Centre de Contrôle du Propriétaire & Gouvernance",
    code: "PORTAL_OWNER",
    description: "Supervision souveraine, encaissements SaaS, matrice RBAC et coupe-circuits nationaux.",
    iconName: "Crown",
    accentColor: "#d97706",
    allowedTabs: ["overview", "visual_identity", "manage_schools", "internal_users", "cyberdefense", "missing_photos", "partner_onboarding", "financial", "emergency", "global_matrix", "audit_log", "servers"],
    defaultRole: "Propriétaire",
    defaultPermissions: OWNER_FULL_PERMISSIONS,
    isSystemDefault: true,
    createdAt: "2026-08-01 08:00",
    createdBy: "Système SmartSchool RDC"
  },
  {
    id: "portal-tech-support",
    name: "Portail Support Technique & Infrastructure",
    code: "PORTAL_STAFF_TECH",
    description: "Monitoring serveurs, cyberdéfense, résolution des incidents et tickets techniques complexes.",
    iconName: "Server",
    accentColor: "#3b82f6",
    allowedTabs: ["overview", "missing_photos", "servers", "support", "cyberdefense", "audit_log"],
    defaultRole: "Personnel Interne",
    defaultPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Support technique"],
    isSystemDefault: true,
    createdAt: "2026-08-01 08:00",
    createdBy: "Système SmartSchool RDC"
  },
  {
    id: "portal-user-support",
    name: "Portail Assistance Utilisateurs & Écoles",
    code: "PORTAL_STAFF_USER_SUPPORT",
    description: "Traitement des tickets écoles, relance photos manquantes et accompagnement des utilisateurs.",
    iconName: "HelpCircle",
    accentColor: "#8b5cf6",
    allowedTabs: ["overview", "missing_photos", "support", "communication"],
    defaultRole: "Personnel Interne",
    defaultPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Support utilisateurs"],
    isSystemDefault: true,
    createdAt: "2026-08-01 08:00",
    createdBy: "Système SmartSchool RDC"
  },
  {
    id: "portal-schools-network",
    name: "Portail Supervision & Déploiement Écoles",
    code: "PORTAL_STAFF_SCHOOLS",
    description: "Intégration de nouveaux établissements partenaires, validation des dossiers et audit conformité.",
    iconName: "Building2",
    accentColor: "#10b981",
    allowedTabs: ["overview", "manage_schools", "partner_onboarding", "missing_photos", "communication"],
    defaultRole: "Personnel Interne",
    defaultPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Responsable des établissements"],
    isSystemDefault: true,
    createdAt: "2026-08-01 08:00",
    createdBy: "Système SmartSchool RDC"
  },
  {
    id: "portal-finance-saas",
    name: "Portail Finances & Réconciliation SaaS",
    code: "PORTAL_STAFF_FINANCE",
    description: "Commissions Mobile Money, validation des flux de reversements et balance comptable plateforme.",
    iconName: "DollarSign",
    accentColor: "#059669",
    allowedTabs: ["overview", "financial", "audit_log"],
    defaultRole: "Personnel Interne",
    defaultPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Comptable de la plateforme"],
    isSystemDefault: true,
    createdAt: "2026-08-01 08:00",
    createdBy: "Système SmartSchool RDC"
  },
  {
    id: "portal-national-commercial",
    name: "Portail Commercial & Partenariats",
    code: "PORTAL_STAFF_COMMERCIAL",
    description: "Prospection, suivi des opportunités provinciales et relations partenariales ministérielles.",
    iconName: "Briefcase",
    accentColor: "#f59e0b",
    allowedTabs: ["overview", "partner_onboarding", "national_stats", "communication"],
    defaultRole: "Personnel Interne",
    defaultPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Responsable commercial"],
    isSystemDefault: true,
    createdAt: "2026-08-01 08:00",
    createdBy: "Système SmartSchool RDC"
  }
];

export const SYSTEM_RESPONSIBILITIES_CATALOG: { id: string; label: string; category: string; description: string }[] = [
  { id: "resp_support_tech", label: "Traitement des Incidents Techniques & Bug Tracking", category: "Technique", description: "Prise en charge des anomalies serveur, base de données et erreurs applicatives." },
  { id: "resp_server_monitoring", label: "Surveillance Active des Serveurs & Backups", category: "Technique", description: "Contrôle des temps de réponse, sauvegardes Firestore et santé des conteneurs Cloud." },
  { id: "resp_missing_photos", label: "Gestion & Relance Photos Manquantes Écoles", category: "Opérations", description: "Détection des élèves/enseignants sans photo et transmission des notifications de rappel." },
  { id: "resp_client_tickets", label: "Assistance Téléphonique & Tchat Direct Écoles", category: "Support", description: "Réponse aux directeurs, secrétaires et enseignants pour l'utilisation quotidienne." },
  { id: "resp_school_onboarding", label: "Enrôlement & Paramétrage Nouveaux Établissements", category: "Écoles", description: "Vérification des codes MINEPST, génération des identifiants promoteurs et licences." },
  { id: "resp_financial_reconciliation", label: "Réconciliation Mobile Money & Reversements", category: "Finances", description: "Vérification des transactions Airtel Money, Orange Money, M-Pesa et reversements aux écoles." },
  { id: "resp_audit_security", label: "Surveillance Sécurité & Détection Intrusions", category: "Sécurité", description: "Contrôle des tentatives d'accès suspectes et application des règles Zero-Trust." },
  { id: "resp_commercial_prospecting", label: "Prospection & Négociation Contrats Écoles", category: "Commercial", description: "Présentation de la solution aux promoteurs scolaires et coordination des démonstrations." },
  { id: "resp_training_schools", label: "Formation Pédagogique des Équipes Écoles", category: "Formation", description: "Animation des ateliers d'appropriation du journal de classe et des bulletins numériques." }
];

export const INITIAL_PLATFORM_STAFF: PlatformStaffMember[] = [
  {
    id: "staff-001",
    nom: "KALONDA",
    postnom: "KAZADI",
    prenom: "Freddy",
    fullName: "Ir Freddy KALONDA KAZADI",
    phone: "+243 994 202 940",
    email: "fredtech37@gmail.com",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
    fonction: "Administrateur plateforme",
    role: "Propriétaire",
    status: "Actif",
    assignedPermissions: OWNER_FULL_PERMISSIONS,
    assignedPortalId: "portal-owner-governance",
    assignedPortalName: "Centre de Contrôle du Propriétaire & Gouvernance",
    responsibilities: [
      "Supervision Souveraine de toute la Plateforme",
      "Gouvernance des Accès & Gestion du Personnel",
      "Validation des Flux Financiers SaaS",
      "Coupe-Circuits d'Urgence & Sécurité Nationale"
    ],
    assignedProvinces: ["Toutes les 26 Provinces RDC"],
    createdAt: "2026-08-01 08:00",
    lastLoginAt: "2026-08-18 09:30",
    notes: "Compte Maître du Propriétaire et Fondateur de SmartSchool RDC"
  },
  {
    id: "staff-002",
    nom: "MUKENDI",
    postnom: "TSHIMANGA",
    prenom: "Alain",
    fullName: "Ing. Alain MUKENDI TSHIMANGA",
    phone: "+243 812 345 678",
    email: "alain.mukendi@smartschool.cd",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250",
    fonction: "Support technique",
    role: "Personnel Interne",
    status: "Actif",
    assignedPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Support technique"],
    assignedPortalId: "portal-tech-support",
    assignedPortalName: "Portail Support Technique & Infrastructure",
    responsibilities: [
      "Traitement des Incidents Techniques & Bug Tracking",
      "Surveillance Active des Serveurs & Backups",
      "Surveillance Sécurité & Détection Intrusions"
    ],
    assignedProvinces: ["Kinshasa", "Kongo Central", "Kwango"],
    createdAt: "2026-08-03 10:15",
    lastLoginAt: "2026-08-17 16:45",
    notes: "Ingénieur d'infrastructure cloud & monitoring réseau"
  },
  {
    id: "staff-003",
    nom: "KAPINGA",
    postnom: "MWAMBA",
    prenom: "Grace",
    fullName: "Mme Grace KAPINGA MWAMBA",
    phone: "+243 897 654 321",
    email: "grace.kapinga@smartschool.cd",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250",
    fonction: "Support utilisateurs",
    role: "Personnel Interne",
    status: "Actif",
    assignedPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Support utilisateurs"],
    assignedPortalId: "portal-user-support",
    assignedPortalName: "Portail Assistance Utilisateurs & Écoles",
    responsibilities: [
      "Assistance Téléphonique & Tchat Direct Écoles",
      "Gestion & Relance Photos Manquantes Écoles",
      "Formation Pédagogique des Équipes Écoles"
    ],
    assignedProvinces: ["Kinshasa", "Haut-Katanga", "Lualaba"],
    createdAt: "2026-08-05 14:20",
    lastLoginAt: "2026-08-18 08:10",
    notes: "Coordination du support école & suivi des photos manquantes"
  },
  {
    id: "staff-004",
    nom: "BONDO",
    postnom: "KASENDE",
    prenom: "Christian",
    fullName: "M. Christian BONDO KASENDE",
    phone: "+243 998 112 233",
    email: "christian.bondo@smartschool.cd",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250",
    fonction: "Comptable de la plateforme",
    role: "Personnel Interne",
    status: "Actif",
    assignedPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Comptable de la plateforme"],
    assignedPortalId: "portal-finance-saas",
    assignedPortalName: "Portail Finances & Réconciliation SaaS",
    responsibilities: [
      "Réconciliation Mobile Money & Reversements",
      "Suivi des Commissions SaaS SmartSchool RDC"
    ],
    assignedProvinces: ["Toutes les 26 Provinces RDC"],
    createdAt: "2026-08-08 09:00",
    lastLoginAt: "2026-08-16 11:20",
    notes: "Gestion des commissions Mobile Money & réconciliation des reversements"
  },
  {
    id: "staff-005",
    nom: "ILUNGA",
    postnom: "MUTOMBO",
    prenom: "Dorcas",
    fullName: "Mme Dorcas ILUNGA MUTOMBO",
    phone: "+243 822 998 877",
    email: "dorcas.ilunga@smartschool.cd",
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250",
    fonction: "Responsable des établissements",
    role: "Personnel Interne",
    status: "Actif",
    assignedPermissions: DEFAULT_PERMISSIONS_BY_FUNCTION["Responsable des établissements"],
    assignedPortalId: "portal-schools-network",
    assignedPortalName: "Portail Supervision & Déploiement Écoles",
    responsibilities: [
      "Enrôlement & Paramétrage Nouveaux Établissements",
      "Prospection & Négociation Contrats Écoles"
    ],
    assignedProvinces: ["Nord-Kivu", "Sud-Kivu", "Ituri", "Maniema"],
    createdAt: "2026-08-10 11:30",
    lastLoginAt: "2026-08-17 14:05",
    notes: "Audit d'intégration des écoles partenaires et liaison académique"
  }
];
